format_version: 10
pipelines:
  mysql:
    group: App-Deployments
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-a66247d:
        git: https://github.com/charanrevops/expense-ansible
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      ssh_password: "AES:ZMfNW8/W1ZWCtKbDHpYEeA==:2eBQqTPVkyYJm1k14CQugQ=="
    stages:
      - DEV:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - run.sh
                    command: bash

      - QA:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -l
                    command: ls
                    run_if: passed

      - STAGE:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -l
                    command: ls
                    run_if: passed

      - PROD:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - run.sh
                    command: bash
                    run_if: passed